### ISSUE TITLE
error unpacking Pak Files

### ISSUE THREAD

**Issue by harisnaeemofficial** [panzi/rust-u4pak#1]
**Comand** :- 
u4pak unpack "base.pak" --encoding --outdir "Extracted" --ignore-magic --force-version=3
**Error** :-
illegal index offset/size: index_offset (12285578166453511617) + index_size (7068329997026018621) > footer_size (9159905)

**Comment by harisnaeemofficial** [comment]
Could you please try this file to unpack?
[base.zip](https://github.com/panzi/rust-u4pak/files/6518881/base.zip)

I Also Tried this command but the error is the same:-

u4pak unpack --dirname-from-compression --ignore-magic --print0 --force-version 4 --outdir "Extracted" "base.pak"
illegal index offset/size: index_offset (12285578166453511617) + index_size (7068329997026018621) > footer_size (9159905)

**Comment by panzi** [comment]
That's not an Unreal Engine 4 Pak file. There don't even seem to be any strings (file names) in there. No idea what that is, sorry.
