### ISSUE TITLE
[Linux] Unable to Unpack GUILTY GEAR -STRIVE- Pak

### ISSUE THREAD

**Issue by sonic2kk** [panzi/rust-u4pak#29]
I am unable to unpack GUILTY GEAR -STRIVE-'s `.pak` file. I am using the command `./u4pak unpack pakchunk0-WindowsNoEditor.pak`.
- When using v1.3.0 stable, it returns `illegal file magic: 0x0`. Adding `--ignore-magic` doesn't return an error but also doesn't do anything, it simply exits.
- When using a Git build from [`458eb6d`](https://github.com/panzi/rust-u4pak/commit/458eb6d53c21f38dfad8592720fe2acf86965210), it returns what I understand to be a Rust library error when trying to decompress: `failed to fill whole buffer`. I have no experience with Rust, but this information was gleaned from [this](https://www.reddit.com/r/rust/comments/b095ag/failed_to_fill_whole_buffer_error_with_bufreader/) Reddit post (the most reliable source of information :wink:). Prefixing the command with `RUST_BACKTRACE=full` doesn't output any more information.

Perhaps the file is using an unsupported compression type? I notice the README explicitly states Gzip and LZ4 compression types aren't supported. I'm not sure what type this game uses, and I'm completely unfamiliar with modding UE4 games. I came across this project in my search.

Let me know if I can provide any more information.

**Comment by Xenira** [comment]
Can you provide the UE engine version?
https://www.reddit.com/r/unrealengine/comments/a9evvq/is_there_a_way_to_check_for_which_version_of/

**Comment by Xenira** [comment]
Regarding the 'failed to fill whole buffer' error:
This is most likely related to an invalid (wrongly read) size field inside the pak causing the the tool to try to read more bytes from the pak then available.
I guess we need to add some more plausibility checks here and provide better error messages.

**Comment by Chaser-0** [comment]
I don't know if it helps, but I'm issuing the same problem with Dragonball Fighter Z (UE 4.17.2) using the windows single-binary version of u4pak. However I can't tell if the pak is encrypted or not. Maybe that's the issue.

**Comment by dunn** [comment]
Seeing the same thing with the Windows build and GBVS (UE 4.21).

**Comment by muk-as** [comment]
failed to fill whole buffer
with game "Throne and Liberty" (UE4.24 with Oodle compression)

**Comment by ghostlyghastly** [comment]
4.27.2.0 plz
