### ISSUE TITLE
Create v1.4.0 release

### ISSUE THREAD

**Issue by Xenira** [panzi/rust-u4pak#36]
- [x] We should create a release v.1.4.0 as v1.3.0 is a lot behind master and the readme in master does not match the 1.3.0 functionality (#32)
- [ ] We should create a dev branch for future development. That way the master always represents the current release
- [ ] ~~The actions should be extended to automatically create a new release on master branch updates~~

**Comment by panzi** [comment]
Agree with the first 2 points, not sure about the 3rd. Wouldn't that spam the release history?
Going to make the the release and develop branch real quick.

**Comment by panzi** [comment]
Are the release notes correct like that? Did I miss something? https://github.com/panzi/rust-u4pak/releases/tag/v1.4.0

**Comment by panzi** [comment]
Will look into automatic releases some other day when I have time. No idea when that will be. Better make a separate issue for that so I can close this one.

**Comment by Xenira** [comment]
Seems about right. Ill create a new issue for the last point.
